version: 2.1

orbs:
  node: circleci/node@14

jobs:
  yarn-install:
    executor: node/default
    steps:
      - checkout
      - node/install:
          install-yarn: true

workflows:
  pr-quality-check:
    jobs:
      - yarn-install
