version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  prepare:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: '14'
      - node/install-packages:
          pkg-manager: yarn
          check-cache: always

workflows:
  pr-quality-check:
    jobs:
      - prepare
