version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  yarn-install:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: '16.13'
      - run: node --version

workflows:
  pr-quality-check:
    jobs:
      - yarn-install
